<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUjetAGN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUjetAGN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUjetAGN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUjetAGN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUjetAGN\App_KernelDevDebugContainer([
    'container.build_hash' => 'UjetAGN',
    'container.build_id' => '3a0009b3',
    'container.build_time' => 1694039945,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUjetAGN');
