<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZSrnDDC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZSrnDDC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZSrnDDC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZSrnDDC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZSrnDDC\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZSrnDDC',
    'container.build_id' => 'fa1fda35',
    'container.build_time' => 1695937239,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZSrnDDC');
