<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMLt6Jxf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMLt6Jxf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMLt6Jxf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMLt6Jxf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMLt6Jxf\App_KernelDevDebugContainer([
    'container.build_hash' => 'MLt6Jxf',
    'container.build_id' => '1a178528',
    'container.build_time' => 1695687062,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMLt6Jxf');
