<?php

namespace ContainerLT3vKGk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ReservaController' shared autowired service.
     *
     * @return \App\Controller\ReservaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ReservaController.php';

        $container->services['App\\Controller\\ReservaController'] = $instance = new \App\Controller\ReservaController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\ReservaController', $container));

        return $instance;
    }
}
