<?php

namespace ContainerUjetAGN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WyNId4aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wyNId4a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wyNId4a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cs' => ['privates', 'App\\Service\\CustomService', 'getCustomServiceService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'cs' => 'App\\Service\\CustomService',
            'doctrine' => '?',
        ]);
    }
}
